In [1]:
import numpy as np

we can create an array and give argument as data type which will be used for memory management

In [2]:
myarr=np.array([[3,6,6]],np.int32)

In [3]:
myarr[0,2]

6

In [4]:
myarr.shape #getting shape of the array 

(1, 3)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1]=45 #assigning values at particular position
print(myarr)

[[ 3 45  6]]


**Array Creation**

In [7]:
#Conversion from python structures
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray
#listarray.size

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
zero_arr=np.zeros((2,6))
zero_arr
#zero_arr.shape

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
rng= np.arange(15) #gives an numpy array of 0 to n-1
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
lspace=np.linspace(1,6,14) #gives linearly spaced elements (1,n,elements)
lspace

array([1.        , 1.38461538, 1.76923077, 2.15384615, 2.53846154,
       2.92307692, 3.30769231, 3.69230769, 4.07692308, 4.46153846,
       4.84615385, 5.23076923, 5.61538462, 6.        ])

In [11]:
emp=np.empty((4,6))
emp_like=np.empty_like(lspace) #assigns same array element to other array
print(lspace)
print(emp_like)

[1.         1.38461538 1.76923077 2.15384615 2.53846154 2.92307692
 3.30769231 3.69230769 4.07692308 4.46153846 4.84615385 5.23076923
 5.61538462 6.        ]
[1.         1.38461538 1.76923077 2.15384615 2.53846154 2.92307692
 3.30769231 3.69230769 4.07692308 4.46153846 4.84615385 5.23076923
 5.61538462 6.        ]


In [12]:
ide=np.identity(9)
print(ide)
ide.shape

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


(9, 9)

In [13]:
#use of reshape and ravel
arr1=np.arange(25)
print(arr1)
arr1=arr1.reshape(5,5)
print(arr1)
arr1=arr1.ravel()
print(arr1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [14]:
#Understanding numpy axis
x=[[1,2,3],[4,5,6],[7,1,0]]
arr2=np.array(x)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [15]:
#summing on axis 0 and 1
s1=arr2.sum(axis=0)  #summing along the columns
s2=arr2.sum(axis=1)  #summing along the rows
print(s1,s2)

[12  8  9] [ 6 15  8]


In [16]:
#Transpose
arr_t=arr2.T
arr_t

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [17]:
# iterator
arr2.flat
for i in arr2.flat:
    print(i)
    
#dimensions
dim=arr2.ndim
print(dim)

#bytes consumed
b_cons=arr2.nbytes
print(b_cons)

1
2
3
4
5
6
7
1
0
2
36


In [18]:
#Use of argmax  , argmin and argsort
arr3=np.array([1,3,4,634,2])
arr3.argmax() #returns index of the maximum element

arr3.argmin() #returns index of the minimum element
 
arr3.argsort() #returns indices of array inorder to sort it ascending

array([0, 4, 1, 2, 3], dtype=int64)

In [19]:
arr2.argmax() #returns element after flatting
a_min=arr2.argmin(axis=0) #returns min elements along axis 0
a_min

#Similar can be done for argmax and arg sort
arr2.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [20]:
#matrix operations
A=np.array([
    [1,3,5],
    [7,8,13]
])

B=np.array([
    [2,8,11],
    [5,9,15]
])

s=A+B #addition
sub=A-B #subtraction

#For matrix operations dimensions should be same of the matrices involved.
print(s)
print(sub)

C=np.array([
    [15,2],
    [13,8],
    [16,21]
])

dot_prod=B.dot(C)
print("Dot product of matrix B and C is: ",dot_prod)
cross_p=np.cross(B,A)
print("Cross product of matrix B and C is: ",cross_p)

[[ 3 11 16]
 [12 17 28]]
[[-1 -5 -6]
 [ 2 -1 -2]]
Dot product of matrix B and C is:  [[310 299]
 [432 397]]
Cross product of matrix B and C is:  [[  7   1  -2]
 [ -3  40 -23]]


In [21]:
#Vector and Matrix Operation
A=np.ones((5,3))
B=5.0*A #scalar multiplication
C=np.random.randint(-5,5,(5,3))

print(A)
print(B)
print(C)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[-2  4  0]
 [-3  2 -5]
 [ 4  2  4]
 [ 0 -1 -1]
 [ 4  0  3]]


In [22]:
#Elemental multiplication
print(A*B)
print(np.multiply(A,B))

A1=1.5*A #scalar multiplication
#Power
print(A1**B)
np.sqrt(A)   
np.power(A,0.2) #power
print(np.exp(A))  #raising each value to e


[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[7.59375 7.59375 7.59375]
 [7.59375 7.59375 7.59375]
 [7.59375 7.59375 7.59375]
 [7.59375 7.59375 7.59375]
 [7.59375 7.59375 7.59375]]
[[2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]]


In [23]:
#Assignment Operations
A+=B
A
#A-=B
#A*=B

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [24]:
#dot product
np.dot(A,B.T)   #transpose is done for making dimensionality check

array([[90., 90., 90., 90., 90.],
       [90., 90., 90., 90., 90.],
       [90., 90., 90., 90., 90.],
       [90., 90., 90., 90., 90.],
       [90., 90., 90., 90., 90.]])

In [25]:
#Calculating Inverse 
D=np.random.randint(-5,5,(5,5))
Dinv=np.linalg.inv(D)
print(Dinv)

print(np.dot(D,Dinv)) #Checking the result

[[ 1.37062937e-01  1.29137529e-01 -3.07692308e-02  1.16550117e-02
   1.16550117e-01]
 [ 1.81818182e-01  4.54545455e-02  1.13992799e-17 -1.81818182e-01
   1.81818182e-01]
 [ 6.57342657e-02  1.84382284e-01  1.07692308e-01 -8.62470862e-02
   1.37529138e-01]
 [-1.11888112e-01 -4.07925408e-02 -7.69230769e-02 -1.63170163e-02
  -1.63170163e-01]
 [-8.81118881e-02 -5.92074592e-02 -1.23076923e-01  1.63170163e-02
   1.63170163e-01]]
[[ 1.00000000e+00 -4.85722573e-17  1.94289029e-16  6.93889390e-18
  -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -1.38777878e-17
   1.11022302e-16]
 [ 5.55111512e-17 -1.80411242e-16  1.00000000e+00  0.00000000e+00
  -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [-2.77555756e-17 -3.46944695e-17 -8.32667268e-17  0.00000000e+00
   1.00000000e+00]]


In [26]:
eigval,eigvec=np.linalg.eig(D)
print("The eigenvalues are and eigen vectors are,",eigval,eigvec)

The eigenvalues are and eigen vectors are, [-5.35219119+5.38237622j -5.35219119-5.38237622j  8.12392402+0.j
  2.29022918+1.97994878j  2.29022918-1.97994878j] [[ 0.34110419-0.07656543j  0.34110419+0.07656543j  0.65019357+0.j
   0.27393602-0.14427461j  0.27393602+0.14427461j]
 [-0.64321779+0.j         -0.64321779-0.j          0.10560636+0.j
   0.4257188 -0.19821926j  0.4257188 +0.19821926j]
 [ 0.2842841 -0.24813032j  0.2842841 +0.24813032j -0.6094946 +0.j
   0.55133301+0.j          0.55133301-0.j        ]
 [-0.08634104-0.54081428j -0.08634104+0.54081428j  0.22658872+0.j
  -0.27054523+0.14239845j -0.27054523-0.14239845j]
 [ 0.06199119-0.13376347j  0.06199119+0.13376347j -0.37850958+0.j
  -0.30134284-0.44200554j -0.30134284+0.44200554j]]
