***Importing TensorFlow***

In [1]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from 'C:\\Users\\SAINATH\\anaconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

***Creating Tensor***

In [2]:
string = tf.Variable("This is string" ,tf.string) #scalar
number =tf.Variable(386 ,tf.int16) 

floating=tf.Variable( 224.36 ,tf.float64) 



***Rank/Degree Tensors***

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor.

In [3]:
rank1_tensor=tf.Variable(["Test"], tf.string)
rank2_tensor=tf.Variable([["Test","ok"], ["Test","ok"]], tf.string)

#To determine rank of tensor
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

***Shape of Tensor***

The shape of a tensor is simply the number of elements that exist in each dimension.

In [4]:
rank2_tensor.shape
#rank1_tensor.shape

TensorShape([2, 2])

***Changing Shape***

The number of elements of a tensor is the product of the sizes of all its shapes.

In [6]:
t1=tf.ones([1,2,3]) #one list containing 2 lists with three elements each
t2 =tf.reshape(t1, [2,3,1]) #two list containing 3 containing one element each

t3=tf.reshape(t1, [3 , -1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
print(t1)
print(t2)
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Types of Tensor 

Variable , Constant , Placeholder , SparseTensor

#Evaluating a Tensor

##c=tf.constant()
with tf.compat.v1.Session() as sess:
    t1.eval()
    #https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session

In [21]:
t4=tf.ones([5,5,5,5])
print(t4)
t4=tf.reshape(t4, [25 ,-1])
print(t4)

tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1.